name: MojoCodeTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download and Install Mojo
        run: |
          curl https://get.modular.com | sh - && 
          modular auth ${{ secrets.MOJO_TOKEN }}
          modular install mojo
      - name: Run Mojo and Check for Errors
        run: |
          mojo ${{ secrets.TEST_FILE }}
