name: MojoCodeTest

env:
  MOJO_HOME: /home/runner/.modular/pkg/packages.modular.com_mojo/bin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          path: /home/runner/.modular
          key: ${{ runner.os }}-modular-${{ hashFiles('**/modular.lock') }}
          restore-keys: |
            ${{ runner.os }}-modular-
      - name: Download and Install Mojo
        run: |
          curl https://get.modular.com | sh - && 
          modular auth ${{ secrets.MOJO_TOKEN }}
          modular install mojo
      - name: Run Mojo and Check for Errors
        run: |
         ${{ env.MOJO_HOME }}/mojo ${{ vars.TEST_FILE }}
